In [12]:
import numpy as np
from numpy import savetxt
import pywt
import cv2 as cv
import pywt.data
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os

In [9]:
def preprocessing(img):
    imgResize = cv.resize(img, (200, 200))
    ret, thresh3 = cv.threshold(img, 120, 255, cv.THRESH_TOZERO)
    thresh3 = cv.cvtColor(thresh3, cv.COLOR_BGR2GRAY)
    ret4, imgSeg4 = cv.threshold(thresh3, 0, 255, cv.THRESH_BINARY+cv.THRESH_OTSU)
    kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
    kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
    img_prewitt3x = cv.filter2D(imgSeg4, -1, kernelx)
    img_prewitt3y = cv.filter2D(imgSeg4, -1, kernely)
    img_canny3 = cv.Canny(img_prewitt3y+img_prewitt3x,100,200)
    
    return img_canny3

In [4]:
def feature_extraction(img):
    preprocessed_image=preprocessing(img)
    c=pywt.wavedec2(preprocessed_image,'db5',mode='periodization',level=2)
    cA2=c[0]#Approximation coefficient
    (cH1,cV1,cD1)=c[-1]#Detailed coefficients at level 1
    (cH2,cV2,cD2)=c[-2]#Detailed coefficients at level 2
    return [cA2,cH1,cV1,cD1,cH2,cV2,cD2]

In [7]:
labels=['MildDemented','ModerateDemented','NonDemented','VeryMildDemented']
def get_data(data_dir):
    data = [] 
    for label in labels: 
        path = os.path.join(data_dir, label)
        class_label = label
        for img in os.listdir(path):
            row=[]
            try:
                img_arr = cv.imread(os.path.join(path, img))
                row=feature_extraction(img_arr)
                row.append(class_label)
                data.append(row)
            except Exception as e:
                print(e)
    return np.array(data)

In [10]:
train = get_data('Alzheimer_s Dataset/train')

In [15]:
test= get_data('Alzheimer_s Dataset/test')

In [16]:
train

array([[array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        ...,
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0.

In [17]:
test

array([[array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]),
        ...,
        array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0.